apiVersion: v1
kind: Service
metadata:
  name: eks-provisioner-api
  namespace: eks-provisioner
  labels:
    app: eks-provisioner-api
spec:
  type: NodePort
  selector:
    app: eks-provisioner-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30800
      name: http
