apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: eks-provisioner
  labels:
    app: eks-provisioner
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_YOUR_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_YOUR_SECRET_ACCESS_KEY"
  AWS_DEFAULT_REGION: "ap-south-1"
